# Generated by Django 2.1.8 on 2020-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('access_page', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterUser',
        ),
    ]
