# Generated by Django 2.1.8 on 2020-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_account', '0003_auto_20200409_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
