# Generated by Django 2.1.8 on 2020-04-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_account', '0004_auto_20200409_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='delete',
            field=models.BooleanField(default=False, verbose_name='删除用户'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='modify',
            field=models.BooleanField(default=False, verbose_name='修改用户'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='regist',
            field=models.BooleanField(default=False, verbose_name='注册用户'),
        ),
    ]
