# Generated by Django 2.1.8 on 2020-04-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftp_account', '0005_auto_20200409_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='regist',
            new_name='register',
        ),
    ]
